'use client';
import { useState } from 'react';
import { ArrowRight, BellRing, CheckCircle2, ChevronDown, HeartPulse, MapPin, ShieldCheck, Smartphone, Waves } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import Dashboard from '@/components/dashboard/Dashboard';

const features = [{icon:BellRing,title:'One-tap SOS',text:'A clear, deliberate path to summon help when every second counts.'},{icon:MapPin,title:'Live location',text:'Share a precise simulated GPS location with the people who need it.'},{icon:Smartphone,title:'Contact cascade',text:'SMS, calls, and audio capture are coordinated in one calm workflow.'}];
export default function Home(){ const [dashboard,setDashboard]=useState(false); const [open,setOpen]=useState<number|null>(null); if(dashboard) return <Dashboard onExit={()=>setDashboard(false)}/>; return <main className="min-h-screen overflow-hidden bg-sand text-ink">
 <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-8"><div className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-coral text-white"><HeartPulse size={20}/></span>SafeGuard</div><div className="hidden items-center gap-8 text-sm text-slate-600 md:flex"><a href="#how">How it works</a><a href="#scope">Future scope</a><a href="#faq">FAQ</a></div><button onClick={()=>setDashboard(true)} className="rounded-full bg-ink px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-navy">Log in <span className="hidden sm:inline">to dashboard</span></button></nav>
 <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 pb-24 pt-12 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-32 lg:pt-24"><div className="absolute left-1/2 top-4 -z-0 h-72 w-72 -translate-x-1/2 rounded-full bg-mint/10 blur-3xl"/><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.6}} className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-mint/30 bg-white/60 px-3 py-1.5 text-xs font-semibold text-teal-700"><span className="h-2 w-2 animate-pulse rounded-full bg-mint"/> Safety, in reach</div><h1 className="max-w-xl font-serif text-6xl leading-[.9] tracking-tight sm:text-7xl">Stay safe.<br/><i>Anytime, anywhere.</i></h1><p className="mt-7 max-w-lg text-lg leading-8 text-slate-600">SafeGuard turns a moment of urgency into a thoughtful, connected response. Your personal emergency companion, simulated for today and ready for real devices tomorrow.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>setDashboard(true)} className="flex items-center gap-2 rounded-full bg-coral px-6 py-3.5 font-semibold text-white shadow-lg shadow-coral/20 transition hover:-translate-y-0.5">Try demo <ArrowRight size={18}/></button><button onClick={()=>setDashboard(true)} className="rounded-full border border-slate-300 bg-white/70 px-6 py-3.5 font-semibold transition hover:bg-white">Open dashboard</button></div><div className="mt-12 flex items-center gap-4 text-sm text-slate-500"><div className="flex -space-x-2"><span className="h-8 w-8 rounded-full border-2 border-sand bg-teal-200"/><span className="h-8 w-8 rounded-full border-2 border-sand bg-orange-200"/><span className="h-8 w-8 rounded-full border-2 border-sand bg-sky-200"/></div>Designed around the people who matter.</div></motion.div>
 <motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{delay:.15,duration:.7}} className="relative mx-auto w-full max-w-md"><div className="absolute -inset-10 rounded-full bg-coral/10 blur-3xl"/><div className="relative overflow-hidden rounded-[2.5rem] border border-white/80 bg-navy p-6 shadow-2xl"><div className="flex items-center justify-between text-xs text-white/60"><span>9:41</span><span className="flex gap-1"><Waves size={13}/><span>100%</span></span></div><div className="mt-10 text-center text-white"><p className="text-xs font-bold tracking-[.2em] text-mint">SAFEGUARD ACTIVE</p><div className="relative mx-auto my-9 grid h-48 w-48 place-items-center rounded-full border border-white/10 bg-white/5"><div className="absolute inset-3 animate-ping rounded-full border border-coral/30"/><div className="grid h-32 w-32 place-items-center rounded-full bg-coral text-2xl font-bold shadow-xl shadow-coral/30">SOS</div></div><p className="font-serif text-3xl">You are not alone.</p><p className="mt-2 text-sm text-white/60">Your network is one tap away.</p></div><div className="mt-10 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-3 text-xs text-white/70"><MapPin className="mb-2 text-mint" size={17}/>Location ready</div><div className="rounded-2xl bg-white/10 p-3 text-xs text-white/70"><ShieldCheck className="mb-2 text-mint" size={17}/>3 contacts armed</div></div></div></div></motion.div></section>
 <section id="how" className="border-y border-slate-200 bg-white/60 py-20"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-coral">BUILT FOR THE MOMENT</p><div className="mt-4 grid gap-8 md:grid-cols-3"><h2 className="font-serif text-4xl leading-none">A composed response to an urgent moment.</h2>{features.map(({icon:Icon,title,text})=><div key={title} className="border-t border-slate-200 pt-5"><Icon className="text-coral"/><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></div>)}</div></div></section>
 <section id="scope" className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-bold tracking-[.2em] text-teal-700">THE ROAD AHEAD</p><h2 className="mt-4 font-serif text-5xl leading-none">A simulation with real-world ambitions.</h2></div><div className="grid grid-cols-2 gap-3">{['ESP32 live link','Accident detection','Wearable support','AWS IoT Core'].map(x=><div key={x} className="rounded-2xl border border-slate-200 bg-white p-5 text-sm font-semibold shadow-soft"><CheckCircle2 className="mb-5 text-mint" size={20}/>{x}<span className="mt-2 block text-xs font-normal text-slate-500">Coming soon</span></div>)}</div></section>
 <section id="faq" className="mx-auto max-w-3xl px-6 pb-24"><h2 className="font-serif text-5xl">Questions, answered.</h2>{['Does SafeGuard contact real people?','Can I connect a real ESP32 later?','Is my personal data secure?'].map((q,i)=><button key={q} onClick={()=>setOpen(open===i?null:i)} className="w-full border-b border-slate-300 py-5 text-left"><span className="flex items-center justify-between font-semibold">{q}<ChevronDown className={open===i?'rotate-180 transition':'transition'} size={18}/></span><AnimatePresence>{open===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden pr-8 pt-3 text-sm leading-6 text-slate-600">This demo uses secure local simulation data. The service layer is designed to connect to Firebase, device telemetry, GPS, and messaging providers when you are ready.</motion.p>}</AnimatePresence></button>)}</section>
 </main> }
